name: angafit
description: "AR based shopping app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_unity_widget: ^2022.2.0
  flutter_stripe: ^11.2.0
  http: ^1.2.1
  camera: ^0.11.0+2
  path_provider: ^2.1.3
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
